spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance-id:${random.value}
    prefer-ip-address: true