spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://49.50.167.208:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance-id:${random.value}
    prefer-ip-address: true

url:
  apiGateway: http://49.50.167.208:8000